//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoodsToGo.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Barangay
    {
        public int BarangayID { get; set; }
        public string Barangay_Name { get; set; }
    }
}
